\set ON_ERROR_STOP on
-- Disposable local database only. Pass candidates_json generated by the API's
-- serializeStoredCandidate helper; all identities and sessions roll back.
BEGIN;
SET LOCAL statement_timeout = '30s';
SET LOCAL lock_timeout = '5s';
CREATE TEMP TABLE phone_identity_smoke_payload AS
SELECT :'candidates_json'::jsonb AS candidates;

DO $$
DECLARE
  v_auth uuid := '00000000-0000-4000-8000-000000000104';
  v_tenant uuid := '00000000-0000-4000-8000-000000000101';
  v_customer uuid := '00000000-0000-4000-8000-000000000102';
  v_employee uuid := '00000000-0000-4000-8000-000000000103';
  v_candidate uuid := '00000000-0000-4000-8000-000000000105';
  v_now timestamptz := clock_timestamp();
  v_claim record;
  v_reserved record;
  v_status text;
  v_candidates jsonb;
BEGIN
  INSERT INTO auth.users(id) VALUES (v_auth);
  INSERT INTO public.tenants(id, name, slug, status)
  VALUES (v_tenant, '手机号登录回归', 'phone-selection-smoke', 'active');
  INSERT INTO public.customers(id, tenant_id, name, phone)
  VALUES (v_customer, v_tenant, '登录回归客户', '13999100101');
  INSERT INTO public.employees(id, tenant_id, name, phone, status)
  VALUES (v_employee, v_tenant, '登录回归员工', '13999100101', 'active');
  INSERT INTO public.sms_verification_codes(phone, scene, code, expired_at)
  VALUES ('13999100101', 'login_identity', '123456', v_now + interval '5 minutes');

  SELECT * INTO STRICT v_claim FROM public.claim_phone_identity_login_verification(
    '13999100101', '123456', v_auth, repeat('a', 64), v_now,
    v_now + interval '5 minutes'
  );
  IF v_claim.status <> 'claimed' THEN RAISE EXCEPTION 'SMS claim failed'; END IF;

  SELECT candidates INTO v_candidates FROM phone_identity_smoke_payload;
  SELECT status INTO STRICT v_status FROM public.begin_phone_identity_selection(
    v_claim.session_id, v_auth, repeat('a', 64), repeat('b', 64),
    '{}'::jsonb, v_candidates, v_now
  );
  IF v_status <> 'ready' OR (
    SELECT count(*) FROM public.phone_identity_login_candidates
    WHERE session_id = v_claim.session_id
      AND binding_state = 'bindable'
      AND display_snapshot->>'role_label' IN ('客户', '员工')
      AND display_snapshot ? 'rebind_kind'
  ) <> 2 THEN RAISE EXCEPTION 'candidate persistence failed'; END IF;

  SELECT * INTO STRICT v_reserved FROM public.reserve_phone_identity_selection(
    repeat('b', 64), v_candidate, v_auth, repeat('a', 64), v_now
  );
  IF v_reserved.status <> 'reserved'
    OR v_reserved.verified_phone <> '13999100101'
    OR v_reserved.customer_id <> v_customer
  THEN RAISE EXCEPTION 'candidate reservation failed'; END IF;

  SELECT status INTO STRICT v_status FROM public.release_phone_identity_selection(
    v_claim.session_id, v_candidate, v_now
  );
  IF v_status <> 'released' THEN RAISE EXCEPTION 'selection release failed'; END IF;

  SELECT status INTO STRICT v_status FROM public.reserve_phone_identity_selection(
    repeat('b', 64), v_candidate, v_auth, repeat('a', 64), v_now
  );
  IF v_status <> 'reserved' THEN RAISE EXCEPTION 'selection retry failed'; END IF;
  SELECT status INTO STRICT v_status FROM public.finalize_phone_identity_selection(
    v_claim.session_id, v_candidate, v_now
  );
  IF v_status <> 'consumed' THEN RAISE EXCEPTION 'selection finalize failed'; END IF;
  SELECT status INTO STRICT v_status FROM public.reserve_phone_identity_selection(
    repeat('b', 64), v_candidate, v_auth, repeat('a', 64), v_now
  );
  IF v_status <> 'same_candidate_consumed'
  THEN RAISE EXCEPTION 'selection replay failed'; END IF;
END;
$$;

ROLLBACK;
