-- Read-only DEV evidence; use existing project/host guards. No writes.
BEGIN READ ONLY; SET LOCAL statement_timeout='15s'; SET LOCAL lock_timeout='3s';
SELECT jsonb_build_object('checked_at',now(),'readonly',current_setting('transaction_read_only'),
'orders',COALESCE((SELECT jsonb_agg(to_jsonb(o)) FROM (SELECT id,tenant_id,warehouse_id,order_no,status,version,reason,created_by_employee_id,created_at,started_at,submitted_at,completed_at,cancelled_at FROM public.warehouse_stocktake_orders WHERE tenant_id='3eebca47-961f-4899-b976-a3d3208d326b' ORDER BY created_at,id LIMIT 10)o),'[]'::jsonb),
'items',COALESCE((SELECT jsonb_agg(to_jsonb(i)) FROM (SELECT id,stocktake_order_id,warehouse_id,supplier_sku_id,book_balance_version,book_quantity,book_value,book_unit_cost,counted_quantity,difference_quantity,difference_reason,unit_cost,amount FROM public.warehouse_stocktake_order_items WHERE tenant_id='3eebca47-961f-4899-b976-a3d3208d326b' ORDER BY stocktake_order_id,line_no LIMIT 10)i),'[]'::jsonb),
'events',COALESCE((SELECT jsonb_agg(to_jsonb(e)) FROM (SELECT id,order_id,command,actor_employee_id,result,created_at FROM public.warehouse_stocktake_command_events WHERE tenant_id='3eebca47-961f-4899-b976-a3d3208d326b' ORDER BY created_at,id LIMIT 30)e),'[]'::jsonb),
'transactions',COALESCE((SELECT jsonb_agg(to_jsonb(t)) FROM (SELECT id,warehouse_id,supplier_sku_id,source_type,source_id,warehouse_stocktake_item_id,transaction_type,quantity_delta,value_delta,created_at FROM public.inventory_transactions WHERE tenant_id='3eebca47-961f-4899-b976-a3d3208d326b' AND source_type='warehouse_stocktake_item' ORDER BY created_at,id LIMIT 10)t),'[]'::jsonb)); COMMIT;

BEGIN READ ONLY; SET LOCAL statement_timeout='15s'; SET LOCAL lock_timeout='3s'; SELECT jsonb_build_object('readonly',current_setting('transaction_read_only'),'checked_at',now(),'events',coalesce((SELECT jsonb_agg(to_jsonb(e)) FROM (SELECT id,resource_type,resource_id,command,from_state,to_state,result_version,created_at FROM public.supplier_command_events WHERE tenant_id='3eebca47-961f-4899-b976-a3d3208d326b' AND created_at>='2026-09-09T12:05:34.139955Z' ORDER BY created_at,id LIMIT 10)e),'[]'::jsonb)); COMMIT;
