import { describe, expect, test } from 'bun:test';

import { ErrorCodes } from './error-codes';

describe('OCR error codes', () => {
  test('exports the stable OCR error contract', () => {
    expect([
      ErrorCodes.OCR_CONFIG_MISSING,
      ErrorCodes.OCR_DISABLED,
      ErrorCodes.OCR_CAPABILITY_UNAVAILABLE,
      ErrorCodes.OCR_FILE_NOT_FOUND,
      ErrorCodes.OCR_FILE_ACCESS_DENIED,
      ErrorCodes.OCR_FILE_FORMAT_UNSUPPORTED,
      ErrorCodes.OCR_FILE_TOO_LARGE,
      ErrorCodes.OCR_DAILY_LIMIT_EXCEEDED,
      ErrorCodes.OCR_IDEMPOTENCY_CONFLICT,
      ErrorCodes.OCR_RECOGNITION_NOT_FOUND,
      ErrorCodes.OCR_RECOGNITION_EXPIRED,
      ErrorCodes.OCR_RECOGNITION_IN_PROGRESS,
      ErrorCodes.OCR_PROVIDER_RATE_LIMITED,
      ErrorCodes.OCR_PROVIDER_FAILED,
      ErrorCodes.OCR_RESULT_INVALID,
      ErrorCodes.OCR_RESULT_ENCRYPTION_KEY_MISSING,
    ]).toEqual([
      'OCR_CONFIG_MISSING',
      'OCR_DISABLED',
      'OCR_CAPABILITY_UNAVAILABLE',
      'OCR_FILE_NOT_FOUND',
      'OCR_FILE_ACCESS_DENIED',
      'OCR_FILE_FORMAT_UNSUPPORTED',
      'OCR_FILE_TOO_LARGE',
      'OCR_DAILY_LIMIT_EXCEEDED',
      'OCR_IDEMPOTENCY_CONFLICT',
      'OCR_RECOGNITION_NOT_FOUND',
      'OCR_RECOGNITION_EXPIRED',
      'OCR_RECOGNITION_IN_PROGRESS',
      'OCR_PROVIDER_RATE_LIMITED',
      'OCR_PROVIDER_FAILED',
      'OCR_RESULT_INVALID',
      'OCR_RESULT_ENCRYPTION_KEY_MISSING',
    ]);
  });
});

describe('branding error codes', () => {
  test('exports the stable branding and tenant entitlement error contract', () => {
    const brandingErrorCodeKeys = Object.keys(ErrorCodes)
      .filter(
        (code) =>
          code.startsWith('BRANDING_') ||
          code.startsWith('TENANT_ENTITLEMENT_'),
      )
      .sort();

    expect([
      ErrorCodes.BRANDING_ENTITLEMENT_REQUIRED,
      ErrorCodes.BRANDING_ENTITLEMENT_SUSPENDED,
      ErrorCodes.BRANDING_ENTITLEMENT_EXPIRED,
      ErrorCodes.BRANDING_ENTITLEMENT_REVOKED,
      ErrorCodes.BRANDING_PROFILE_VERSION_CONFLICT,
      ErrorCodes.BRANDING_PROFILE_INCOMPLETE,
      ErrorCodes.BRANDING_LOGO_FILE_NOT_FOUND,
      ErrorCodes.BRANDING_LOGO_FILE_INVALID,
      ErrorCodes.TENANT_ENTITLEMENT_NOT_FOUND,
      ErrorCodes.TENANT_ENTITLEMENT_VERSION_CONFLICT,
      ErrorCodes.TENANT_ENTITLEMENT_STATE_CONFLICT,
    ]).toEqual([
      'BRANDING_ENTITLEMENT_REQUIRED',
      'BRANDING_ENTITLEMENT_SUSPENDED',
      'BRANDING_ENTITLEMENT_EXPIRED',
      'BRANDING_ENTITLEMENT_REVOKED',
      'BRANDING_PROFILE_VERSION_CONFLICT',
      'BRANDING_PROFILE_INCOMPLETE',
      'BRANDING_LOGO_FILE_NOT_FOUND',
      'BRANDING_LOGO_FILE_INVALID',
      'TENANT_ENTITLEMENT_NOT_FOUND',
      'TENANT_ENTITLEMENT_VERSION_CONFLICT',
      'TENANT_ENTITLEMENT_STATE_CONFLICT',
    ]);
    expect(brandingErrorCodeKeys).toEqual([
      'BRANDING_ENTITLEMENT_EXPIRED',
      'BRANDING_ENTITLEMENT_REQUIRED',
      'BRANDING_ENTITLEMENT_REVOKED',
      'BRANDING_ENTITLEMENT_SUSPENDED',
      'BRANDING_LOGO_FILE_INVALID',
      'BRANDING_LOGO_FILE_NOT_FOUND',
      'BRANDING_PROFILE_INCOMPLETE',
      'BRANDING_PROFILE_VERSION_CONFLICT',
      'TENANT_ENTITLEMENT_NOT_FOUND',
      'TENANT_ENTITLEMENT_STATE_CONFLICT',
      'TENANT_ENTITLEMENT_VERSION_CONFLICT',
    ]);
  });
});

describe('platform service sales error codes', () => {
  test('exports the stable service order and product error contract', () => {
    expect([
      ErrorCodes.SERVICE_PRODUCT_NOT_FOUND,
      ErrorCodes.SERVICE_TERMS_VERSION_STALE,
      ErrorCodes.SERVICE_ORDER_NOT_FOUND,
      ErrorCodes.SERVICE_ORDER_INVALID_STATE,
      ErrorCodes.SERVICE_ORDER_VERSION_CONFLICT,
      ErrorCodes.SERVICE_ORDER_IDEMPOTENCY_CONFLICT,
      ErrorCodes.SERVICE_ORDER_FORBIDDEN,
      ErrorCodes.PAYER_OPENID_REQUIRED,
      ErrorCodes.SERVICE_PAYMENT_CONFIG_INVALID,
      ErrorCodes.SERVICE_PAYMENT_PREPAY_FAILED,
      ErrorCodes.SERVICE_REFUND_ALREADY_PENDING,
      ErrorCodes.SERVICE_PRODUCT_VERSION_CONFLICT,
      ErrorCodes.SERVICE_PRODUCT_PUBLISH_REQUIRED,
      ErrorCodes.SERVICE_WORK_ORDER_NOT_FOUND,
      ErrorCodes.SERVICE_WORK_ORDER_VERSION_CONFLICT,
      ErrorCodes.SERVICE_ACCEPTANCE_INVALID_STATE,
      ErrorCodes.SERVICE_FULFILLMENT_ATTACHMENT_INVALID,
    ]).toEqual([
      'SERVICE_PRODUCT_NOT_FOUND',
      'SERVICE_TERMS_VERSION_STALE',
      'SERVICE_ORDER_NOT_FOUND',
      'SERVICE_ORDER_INVALID_STATE',
      'SERVICE_ORDER_VERSION_CONFLICT',
      'SERVICE_ORDER_IDEMPOTENCY_CONFLICT',
      'SERVICE_ORDER_FORBIDDEN',
      'PAYER_OPENID_REQUIRED',
      'SERVICE_PAYMENT_CONFIG_INVALID',
      'SERVICE_PAYMENT_PREPAY_FAILED',
      'SERVICE_REFUND_ALREADY_PENDING',
      'SERVICE_PRODUCT_VERSION_CONFLICT',
      'SERVICE_PRODUCT_PUBLISH_REQUIRED',
      'SERVICE_WORK_ORDER_NOT_FOUND',
      'SERVICE_WORK_ORDER_VERSION_CONFLICT',
      'SERVICE_ACCEPTANCE_INVALID_STATE',
      'SERVICE_FULFILLMENT_ATTACHMENT_INVALID',
    ]);
  });
});

describe('tenant private supplier error codes', () => {
  test('exports the stable ownership, code, state, and access contract', () => {
    expect([
      ErrorCodes.SUPPLIER_OWNERSHIP_CONFLICT,
      ErrorCodes.SUPPLIER_CODE_CONFLICT,
      ErrorCodes.SUPPLIER_CODE_ALLOCATION_CONFLICT,
      ErrorCodes.TENANT_SUPPLIER_NOT_FOUND,
      ErrorCodes.TENANT_SUPPLIER_STATE_CONFLICT,
      ErrorCodes.PRIVATE_RESOURCE_FORBIDDEN,
    ]).toEqual([
      'SUPPLIER_OWNERSHIP_CONFLICT',
      'SUPPLIER_CODE_CONFLICT',
      'SUPPLIER_CODE_ALLOCATION_CONFLICT',
      'TENANT_SUPPLIER_NOT_FOUND',
      'TENANT_SUPPLIER_STATE_CONFLICT',
      'PRIVATE_RESOURCE_FORBIDDEN',
    ]);
  });
});

describe('supplier catalog error codes', () => {
  test('exports the stable catalog, spec, and conversion contract', () => {
    expect([
      ErrorCodes.SHARED_RESOURCE_READ_ONLY,
      ErrorCodes.PRODUCT_OWNERSHIP_CONFLICT,
      ErrorCodes.CATEGORY_OWNERSHIP_CONFLICT,
      ErrorCodes.BRAND_OWNERSHIP_CONFLICT,
      ErrorCodes.SPEC_TEMPLATE_VALIDATION_ERROR,
      ErrorCodes.UNIT_CONVERSION_INVALID,
    ]).toEqual([
      'SHARED_RESOURCE_READ_ONLY',
      'PRODUCT_OWNERSHIP_CONFLICT',
      'CATEGORY_OWNERSHIP_CONFLICT',
      'BRAND_OWNERSHIP_CONFLICT',
      'SPEC_TEMPLATE_VALIDATION_ERROR',
      'UNIT_CONVERSION_INVALID',
    ]);
  });
});
