import { describe, expect, test } from 'bun:test';

import { ErrorCodes } from './error-codes';

describe('OCR error codes', () => {
  test('exports the stable OCR error contract', () => {
    expect([
      ErrorCodes.OCR_CONFIG_MISSING,
      ErrorCodes.OCR_DISABLED,
      ErrorCodes.OCR_CAPABILITY_UNAVAILABLE,
      ErrorCodes.OCR_FILE_NOT_FOUND,
      ErrorCodes.OCR_FILE_ACCESS_DENIED,
      ErrorCodes.OCR_FILE_FORMAT_UNSUPPORTED,
      ErrorCodes.OCR_FILE_TOO_LARGE,
      ErrorCodes.OCR_DAILY_LIMIT_EXCEEDED,
      ErrorCodes.OCR_IDEMPOTENCY_CONFLICT,
      ErrorCodes.OCR_RECOGNITION_NOT_FOUND,
      ErrorCodes.OCR_RECOGNITION_EXPIRED,
      ErrorCodes.OCR_RECOGNITION_IN_PROGRESS,
      ErrorCodes.OCR_PROVIDER_RATE_LIMITED,
      ErrorCodes.OCR_PROVIDER_FAILED,
      ErrorCodes.OCR_RESULT_INVALID,
      ErrorCodes.OCR_RESULT_ENCRYPTION_KEY_MISSING,
    ]).toEqual([
      'OCR_CONFIG_MISSING',
      'OCR_DISABLED',
      'OCR_CAPABILITY_UNAVAILABLE',
      'OCR_FILE_NOT_FOUND',
      'OCR_FILE_ACCESS_DENIED',
      'OCR_FILE_FORMAT_UNSUPPORTED',
      'OCR_FILE_TOO_LARGE',
      'OCR_DAILY_LIMIT_EXCEEDED',
      'OCR_IDEMPOTENCY_CONFLICT',
      'OCR_RECOGNITION_NOT_FOUND',
      'OCR_RECOGNITION_EXPIRED',
      'OCR_RECOGNITION_IN_PROGRESS',
      'OCR_PROVIDER_RATE_LIMITED',
      'OCR_PROVIDER_FAILED',
      'OCR_RESULT_INVALID',
      'OCR_RESULT_ENCRYPTION_KEY_MISSING',
    ]);
  });
});

describe('branding error codes', () => {
  test('exports the stable branding and tenant entitlement error contract', () => {
    expect([
      ErrorCodes.BRANDING_ENTITLEMENT_REQUIRED,
      ErrorCodes.BRANDING_ENTITLEMENT_SUSPENDED,
      ErrorCodes.BRANDING_ENTITLEMENT_EXPIRED,
      ErrorCodes.BRANDING_ENTITLEMENT_REVOKED,
      ErrorCodes.BRANDING_PROFILE_VERSION_CONFLICT,
      ErrorCodes.BRANDING_PROFILE_INCOMPLETE,
      ErrorCodes.BRANDING_LOGO_FILE_NOT_FOUND,
      ErrorCodes.BRANDING_LOGO_FILE_INVALID,
      ErrorCodes.TENANT_ENTITLEMENT_NOT_FOUND,
      ErrorCodes.TENANT_ENTITLEMENT_VERSION_CONFLICT,
      ErrorCodes.TENANT_ENTITLEMENT_STATE_CONFLICT,
    ]).toEqual([
      'BRANDING_ENTITLEMENT_REQUIRED',
      'BRANDING_ENTITLEMENT_SUSPENDED',
      'BRANDING_ENTITLEMENT_EXPIRED',
      'BRANDING_ENTITLEMENT_REVOKED',
      'BRANDING_PROFILE_VERSION_CONFLICT',
      'BRANDING_PROFILE_INCOMPLETE',
      'BRANDING_LOGO_FILE_NOT_FOUND',
      'BRANDING_LOGO_FILE_INVALID',
      'TENANT_ENTITLEMENT_NOT_FOUND',
      'TENANT_ENTITLEMENT_VERSION_CONFLICT',
      'TENANT_ENTITLEMENT_STATE_CONFLICT',
    ]);
  });
});
