export const DEPARTMENT_CODE_VALUES = [
  'BOARD',
  'EXEC_OFFICE',
  'SALES',
  'MARKETING',
  'DESIGN',
  'PROJECT',
  'PROCURE',
  'AFTER_SALE',
  'PRODUCT',
  'TECH',
  'IT',
  'BIM_CENTER',
  'SUPPLY_CHAIN',
  'LOGISTICS',
  'WAREHOUSE',
  'FACTORY',
  'PROJECT_MGT',
  'QUALITY_SUPERVISION',
  'SAFETY',
  'ACCEPTANCE',
  'MAINTENANCE',
  'ADMIN',
  'FINANCE',
  'LEGAL',
  'COMPLIANCE',
  'INTERNAL_AUDIT',
  'BRAND',
  'PUBLIC_RELATIONS',
  'DIGITAL_MARKETING',
  'SELF_MEDIA',
  'CHANNEL',
  'COMMUNITY',
  'CUSTOMER_SERVICE',
  'CUSTOMER_SUCCESS',
  'COMPLAINTS',
  'STRATEGY',
  'INVESTOR',
  'BUSINESS_DEV',
  'PMO',
  'TRAINING',
  'OPERATIONS',
  'DATA_CENTER',
] as const;

export type DepartmentCode = (typeof DEPARTMENT_CODE_VALUES)[number];

export interface DepartmentConfigItem {
  label: string;
  type: 'default' | 'primary' | 'success' | 'warning' | 'danger';
}

export const DepartmentConfig: Record<DepartmentCode, DepartmentConfigItem> = {
  BOARD: { label: '董事会', type: 'danger' },
  EXEC_OFFICE: { label: '总裁办/总经理办公室', type: 'danger' },
  SALES: { label: '销售部/客户部', type: 'primary' },
  MARKETING: { label: '市场部', type: 'primary' },
  DESIGN: { label: '设计部', type: 'warning' },
  PROJECT: { label: '工程部', type: 'danger' },
  PROCURE: { label: '采购部', type: 'primary' },
  AFTER_SALE: { label: '售后部/维保部', type: 'default' },
  PRODUCT: { label: '产品部', type: 'primary' },
  TECH: { label: '技术研发部', type: 'success' },
  IT: { label: '信息技术部', type: 'success' },
  BIM_CENTER: { label: 'BIM中心', type: 'success' },
  SUPPLY_CHAIN: { label: '供应链管理部', type: 'primary' },
  LOGISTICS: { label: '物流部', type: 'primary' },
  WAREHOUSE: { label: '仓储部', type: 'primary' },
  FACTORY: { label: '工厂/生产基地', type: 'warning' },
  PROJECT_MGT: { label: '工程项目管理部', type: 'danger' },
  QUALITY_SUPERVISION: { label: '质量监理部', type: 'success' },
  SAFETY: { label: '安全监察部', type: 'danger' },
  ACCEPTANCE: { label: '竣工验收部', type: 'warning' },
  MAINTENANCE: { label: '维修保养部', type: 'warning' },
  ADMIN: { label: '行政人事部', type: 'default' },
  FINANCE: { label: '财务部', type: 'success' },
  LEGAL: { label: '法务部', type: 'default' },
  COMPLIANCE: { label: '合规部', type: 'default' },
  INTERNAL_AUDIT: { label: '内审部', type: 'default' },
  BRAND: { label: '品牌管理部', type: 'primary' },
  PUBLIC_RELATIONS: { label: '公关部', type: 'primary' },
  DIGITAL_MARKETING: { label: '数字营销部', type: 'primary' },
  SELF_MEDIA: { label: '自媒体部', type: 'success' },
  CHANNEL: { label: '渠道部', type: 'primary' },
  COMMUNITY: { label: '社区运营部', type: 'primary' },
  CUSTOMER_SERVICE: { label: '客服部', type: 'default' },
  CUSTOMER_SUCCESS: { label: '客户成功部', type: 'success' },
  COMPLAINTS: { label: '客诉处理部', type: 'warning' },
  STRATEGY: { label: '战略发展部', type: 'danger' },
  INVESTOR: { label: '投资者关系部', type: 'danger' },
  BUSINESS_DEV: { label: '商务拓展部', type: 'primary' },
  PMO: { label: '项目管理办公室', type: 'warning' },
  TRAINING: { label: '培训部', type: 'default' },
  OPERATIONS: { label: '运营部', type: 'success' },
  DATA_CENTER: { label: '数据中心', type: 'success' },
};

export const isDepartmentCode = (
  value: string | null | undefined,
): value is DepartmentCode =>
  typeof value === 'string' &&
  DEPARTMENT_CODE_VALUES.includes(value as DepartmentCode);
