export const WECHAT_PAY_APPLYMENT_TENANT_REVIEW_BLOCKER_CODES = [
  'APPLYMENT_SENSITIVE_PAYLOAD_MISSING',
  'APPLYMENT_REQUIRED_ATTACHMENT_MISSING',
  'APPLYMENT_REQUIRED_FIELD_MISSING',
  'APPLYMENT_MEDIA_METADATA_INVALID',
  'APPLYMENT_MEDIA_CATEGORY_INVALID',
  'APPLYMENT_MEDIA_CATEGORY_DUPLICATE',
  'APPLYMENT_OBJECT_KEY_INVALID',
  'APPLYMENT_MEDIA_TYPE_UNSUPPORTED',
  'APPLYMENT_MEDIA_SIZE_INVALID',
  'APPLYMENT_MEDIA_TOO_LARGE',
  'APPLYMENT_SENSITIVE_PAYLOAD_VERSION_MISMATCH',
  'APPLYMENT_SENSITIVE_PAYLOAD_UNREADABLE',
  'APPLYMENT_ENTERPRISE_ACCOUNT_TYPE_INVALID',
  'APPLYMENT_SETTLEMENT_RULE_INVALID',
  'APPLYMENT_ATTACHMENT_OCR_REVIEW_REQUIRED',
  'APPLYMENT_ATTACHMENT_OCR_RECOGNITION_MISMATCH',
  'PREFLIGHT_DATA_ACCESS_FAILED',
] as const;

export const WECHAT_PAY_APPLYMENT_FORMAL_ONLY_BLOCKER_CODES = [
  'APPLYMENT_STATUS_NOT_SUBMITTABLE',
  'APPLYMENT_SUBMISSION_LEASE_INVALID',
  'APPLYMENT_SUBMISSION_IN_PROGRESS',
  'APPLYMENT_NOT_FOUND',
  'PREFLIGHT_INTERNAL_ERROR',
  'PLATFORM_PAYMENT_CONFIG_MISSING',
  'PLATFORM_PAYMENT_CONFIG_INACTIVE',
  'PLATFORM_PAYMENT_CONFIG_NOT_VALIDATED',
  'PLATFORM_PAYMENT_MERCHANT_MODE_MISMATCH',
  'PLATFORM_PAYMENT_MERCHANT_ID_MISSING',
  'PLATFORM_PAYMENT_APP_ID_MISSING',
  'PLATFORM_PAYMENT_SECRET_REF_MISSING',
  'PLATFORM_PAYMENT_SECRET_BUNDLE_REVISION_MISSING',
  'PLATFORM_PAYMENT_SERIAL_NO_MISSING',
  'PLATFORM_PAYMENT_CALLBACK_URL_MISSING',
  'PLATFORM_PAYMENT_CALLBACK_URL_INVALID',
  'PLATFORM_PAYMENT_REQUIRED_CHANNELS_MISSING',
  'PLATFORM_PAYMENT_PROFILE_NOT_READY',
  'WECHAT_PAY_APPLYMENT_PROFILE_INCOMPLETE',
  'WECHAT_PAY_SECRET_REF_REQUIRED',
  'WECHAT_PAY_SECRET_BUNDLE_INVALID',
] as const;

export const WECHAT_PAY_APPLYMENT_KNOWN_BLOCKER_CODES = [
  ...WECHAT_PAY_APPLYMENT_TENANT_REVIEW_BLOCKER_CODES,
  ...WECHAT_PAY_APPLYMENT_FORMAL_ONLY_BLOCKER_CODES,
] as const;

export type WechatPayApplymentKnownBlockerCode =
  typeof WECHAT_PAY_APPLYMENT_KNOWN_BLOCKER_CODES[number];

export type WechatPayApplymentBlockerCode =
  | WechatPayApplymentKnownBlockerCode
  | (string & Record<never, never>);

const KNOWN_BLOCKER_CODES = new Set<string>(
  WECHAT_PAY_APPLYMENT_KNOWN_BLOCKER_CODES,
);

export function isWechatPayApplymentKnownBlockerCode(
  code: string,
): code is WechatPayApplymentKnownBlockerCode {
  return KNOWN_BLOCKER_CODES.has(code);
}
