import type { SettingDefinition } from './shared';

export const DEFINITIONS_SMS: SettingDefinition[] = [
  {
    key: "SMS_PROVIDER",
    groupCode: "sms",
    name: "短信服务商",
    description: "平台短信服务商。可在页面选择模拟发送、禁用发送、阿里云短信或腾讯云短信。",
    valueType: "string",
    envNames: ["SMS_PROVIDER"],
    defaultValue: "mock",
  },
  {
    key: "SMS_CHANNEL_MODE",
    groupCode: "sms",
    name: "租户短信通道模式",
    description: "租户短信通道模式：继承平台、使用租户自有阿里云或使用租户自有腾讯云。",
    valueType: "string",
    envNames: ["SMS_CHANNEL_MODE"],
    defaultValue: "platform",
  },
  {
    key: "ALIYUN_SMS_SIGN_NAME",
    groupCode: "sms",
    name: "阿里云短信签名",
    description: "阿里云短信签名名称。",
    valueType: "string",
    envNames: ["ALIYUN_SMS_SIGN_NAME"],
  },
  {
    key: "ALIBABA_CLOUD_ACCESS_KEY_ID",
    groupCode: "sms",
    name: "阿里云访问密钥编号",
    description: "阿里云短信访问密钥编号，加密存储。",
    valueType: "string",
    envNames: ["ALIBABA_CLOUD_ACCESS_KEY_ID"],
    isSecret: true,
  },
  {
    key: "ALIBABA_CLOUD_ACCESS_KEY_SECRET",
    groupCode: "sms",
    name: "阿里云访问密钥",
    description: "阿里云短信访问密钥，加密存储。",
    valueType: "string",
    envNames: ["ALIBABA_CLOUD_ACCESS_KEY_SECRET"],
    isSecret: true,
  },
  {
    key: "ALIYUN_SMS_TEMPLATE_CODE_BIND_CUSTOMER",
    groupCode: "sms",
    name: "客户绑定短信模板",
    description: "客户绑定手机号验证码模板编号。",
    valueType: "string",
    envNames: ["ALIYUN_SMS_TEMPLATE_CODE_BIND_CUSTOMER"],
  },
  {
    key: "ALIYUN_SMS_TEMPLATE_CODE_BIND_EMPLOYEE",
    groupCode: "sms",
    name: "员工绑定短信模板",
    description: "员工绑定手机号验证码模板编号。",
    valueType: "string",
    envNames: ["ALIYUN_SMS_TEMPLATE_CODE_BIND_EMPLOYEE"],
  },
  {
    key: "ALIYUN_SMS_TEMPLATE_CODE_ADMIN_LOGIN",
    groupCode: "sms",
    name: "后台登录短信模板",
    description: "后台管理员登录验证码模板编号；为空时回退员工绑定模板。",
    valueType: "string",
    envNames: ["ALIYUN_SMS_TEMPLATE_CODE_ADMIN_LOGIN"],
  },
  {
    key: "ALIYUN_SMS_TEMPLATE_CODE_PROJECT_ACCEPTANCE",
    groupCode: "sms",
    name: "项目验收通知短信模板",
    description: "领导复核通过后发送给客户的项目验收通知模板编号。模板变量建议包含阶段名称、链接和有效期。",
    valueType: "string",
    envNames: ["ALIYUN_SMS_TEMPLATE_CODE_PROJECT_ACCEPTANCE"],
  },
  {
    key: "PROJECT_ACCEPTANCE_SMS_EXPIRE_HOURS",
    groupCode: "sms",
    name: "项目验收短信链接有效期",
    description: "项目验收短信凭证有效期，单位小时。",
    valueType: "number",
    envNames: ["PROJECT_ACCEPTANCE_SMS_EXPIRE_HOURS"],
    defaultValue: "72",
  },
  {
    key: "PROJECT_ACCEPTANCE_SMS_LINK_TYPE",
    groupCode: "sms",
    name: "项目验收短信链接类型",
    description: "支持小程序短链或微信直达链接；微信直达链接依赖微信小程序应用编号和密钥。",
    valueType: "string",
    envNames: ["PROJECT_ACCEPTANCE_SMS_LINK_TYPE"],
    defaultValue: "scheme",
  },
  {
    key: "TENCENT_SMS_SECRET_ID",
    groupCode: "sms",
    name: "腾讯云短信密钥编号",
    description: "腾讯云短信密钥编号，加密存储。",
    valueType: "string",
    envNames: ["TENCENT_SMS_SECRET_ID"],
    isSecret: true,
  },
  {
    key: "TENCENT_SMS_SECRET_KEY",
    groupCode: "sms",
    name: "腾讯云短信密钥",
    description: "腾讯云短信密钥，加密存储。",
    valueType: "string",
    envNames: ["TENCENT_SMS_SECRET_KEY"],
    isSecret: true,
  },
  {
    key: "TENCENT_SMS_REGION",
    groupCode: "sms",
    name: "腾讯云短信区域",
    description: "腾讯云短信接口区域。",
    valueType: "string",
    envNames: ["TENCENT_SMS_REGION"],
    defaultValue: "ap-guangzhou",
  },
  {
    key: "TENCENT_SMS_ENDPOINT",
    groupCode: "sms",
    name: "腾讯云短信接口域名",
    description: "腾讯云短信接口域名。",
    valueType: "string",
    envNames: ["TENCENT_SMS_ENDPOINT"],
    defaultValue: "sms.tencentcloudapi.com",
  },
  {
    key: "TENCENT_SMS_SDK_APP_ID",
    groupCode: "sms",
    name: "腾讯云短信应用编号",
    description: "腾讯云短信应用编号。",
    valueType: "string",
    envNames: ["TENCENT_SMS_SDK_APP_ID"],
  },
  {
    key: "TENCENT_SMS_SIGN_NAME",
    groupCode: "sms",
    name: "腾讯云短信签名",
    description: "腾讯云短信签名名称。",
    valueType: "string",
    envNames: ["TENCENT_SMS_SIGN_NAME"],
  },
  {
    key: "TENCENT_SMS_TEMPLATE_ID_BIND_CUSTOMER",
    groupCode: "sms",
    name: "腾讯云客户绑定模板",
    description: "客户绑定手机号验证码模板 ID。",
    valueType: "string",
    envNames: ["TENCENT_SMS_TEMPLATE_ID_BIND_CUSTOMER"],
  },
  {
    key: "TENCENT_SMS_TEMPLATE_ID_BIND_EMPLOYEE",
    groupCode: "sms",
    name: "腾讯云员工绑定模板",
    description: "员工绑定手机号验证码模板 ID。",
    valueType: "string",
    envNames: ["TENCENT_SMS_TEMPLATE_ID_BIND_EMPLOYEE"],
  },
  {
    key: "TENCENT_SMS_TEMPLATE_ID_ADMIN_LOGIN",
    groupCode: "sms",
    name: "腾讯云后台登录模板",
    description: "后台管理员登录验证码模板 ID；为空时回退员工绑定模板。",
    valueType: "string",
    envNames: ["TENCENT_SMS_TEMPLATE_ID_ADMIN_LOGIN"],
  },
  {
    key: "TENCENT_SMS_TEMPLATE_ID_PROJECT_ACCEPTANCE",
    groupCode: "sms",
    name: "腾讯云项目验收通知模板",
    description: "领导复核通过后发送给客户的项目验收通知模板 ID。",
    valueType: "string",
    envNames: ["TENCENT_SMS_TEMPLATE_ID_PROJECT_ACCEPTANCE"],
  },

];
