import type { SettingDefinition } from "./shared";

export const DEFINITIONS_OCR_VISITOR: SettingDefinition[] = [
  {
    key: "TENCENT_OCR_TENANT_ONBOARDING_ENABLED",
    groupCode: "ocr",
    name: "装企入驻营业执照识别",
    description: "控制 visitor 是否可使用装企入驻营业执照识别。",
    valueType: "boolean",
    envNames: ["TENCENT_OCR_TENANT_ONBOARDING_ENABLED"],
    defaultValue: "false",
  },
  {
    key: "TENCENT_OCR_VISITOR_DAILY_LIMIT",
    groupCode: "ocr",
    name: "访客 OCR 单日额度",
    description: "每个 visitor 每个 UTC 自然日可调用的 OCR 次数。",
    valueType: "number",
    envNames: ["TENCENT_OCR_VISITOR_DAILY_LIMIT"],
    defaultValue: "5",
  },
  {
    key: "TENCENT_OCR_VISITOR_IP_WINDOW_SECONDS",
    groupCode: "ocr",
    name: "访客 OCR IP 窗口秒数",
    description: "访客 OCR 按可信客户端 IP 限流的固定窗口秒数。",
    valueType: "number",
    envNames: ["TENCENT_OCR_VISITOR_IP_WINDOW_SECONDS"],
    defaultValue: "60",
  },
  {
    key: "TENCENT_OCR_VISITOR_IP_WINDOW_LIMIT",
    groupCode: "ocr",
    name: "访客 OCR IP 窗口额度",
    description: "同一可信客户端 IP 在固定窗口内可调用的 OCR 次数。",
    valueType: "number",
    envNames: ["TENCENT_OCR_VISITOR_IP_WINDOW_LIMIT"],
    defaultValue: "20",
  },
  {
    key: "TENCENT_OCR_VISITOR_PROCESSING_LEASE_SECONDS",
    groupCode: "ocr",
    name: "访客 OCR 处理租约秒数",
    description: "visitor processing 记录允许占用并发的最长时间。",
    valueType: "number",
    envNames: ["TENCENT_OCR_VISITOR_PROCESSING_LEASE_SECONDS"],
    defaultValue: "30",
  },
  {
    key: "TENCENT_OCR_VISITOR_CONCURRENCY_LIMIT",
    groupCode: "ocr",
    name: "单访客 OCR 并发上限",
    description: "单个 visitor 同时处于 processing 的识别数量上限。",
    valueType: "number",
    envNames: ["TENCENT_OCR_VISITOR_CONCURRENCY_LIMIT"],
    defaultValue: "1",
  },
  {
    key: "TENCENT_OCR_VISITOR_GLOBAL_CONCURRENCY_LIMIT",
    groupCode: "ocr",
    name: "访客 OCR 总并发上限",
    description: "全部 visitor 同时处于 processing 的识别数量上限。",
    valueType: "number",
    envNames: ["TENCENT_OCR_VISITOR_GLOBAL_CONCURRENCY_LIMIT"],
    defaultValue: "8",
  },
];
