import type { SettingDefinition } from './shared';

export const DEFINITIONS_WECHAT_NOTIFY: SettingDefinition[] = [
  {
    key: "WECHAT_SHARE_CAMPAIGN_PAGE",
    groupCode: "wechat",
    name: "微信助力页路径",
    description: "微信小程序客户日志助力页路径。",
    valueType: "string",
    envNames: ["WECHAT_SHARE_CAMPAIGN_PAGE"],
    defaultValue: "pages/share-campaign/index",
  },
  {
    key: "WECHAT_APPID",
    groupCode: "wechat",
    name: "微信小程序应用编号",
    description: "微信小程序应用编号，加密存储。",
    valueType: "string",
    envNames: ["WECHAT_APPID"],
    isSecret: true,
  },
  {
    key: "WECHAT_MINIPROGRAM_ORIGINAL_ID",
    groupCode: "wechat",
    name: "微信小程序原始 ID",
    description: "微信消息推送 ToUserName 对应的小程序原始 ID（gh_ 开头、最长 128 字符），不得填写 AppID。",
    valueType: "string",
    envNames: ["WECHAT_MINIPROGRAM_ORIGINAL_ID"],
  },
  {
    key: "WECHAT_SECRET",
    groupCode: "wechat",
    name: "微信小程序密钥",
    description: "微信小程序密钥，加密存储。",
    valueType: "string",
    envNames: ["WECHAT_SECRET"],
    isSecret: true,
  },
  {
    key: "WECHAT_VIRTUAL_PAYMENT_MESSAGE_TOKEN",
    groupCode: "payment",
    name: "微信虚拟支付消息令牌",
    description: "仅用于微信小程序虚拟支付消息推送的非空 SHA-1 验签令牌（最长 512 字符），加密存储；不得复用 AppSecret 或虚拟支付 AppKey。",
    valueType: "string",
    envNames: ["WECHAT_VIRTUAL_PAYMENT_MESSAGE_TOKEN"],
    isSecret: true,
  },
  {
    key: "WECHAT_SHARE_CAMPAIGN_CLAIM_VOUCHER_PAGE",
    groupCode: "wechat",
    name: "微信领券页路径",
    description: "微信小程序领券页路径。",
    valueType: "string",
    envNames: ["WECHAT_SHARE_CAMPAIGN_CLAIM_VOUCHER_PAGE"],
    defaultValue: "pages/share-campaign-claim-voucher/index",
  },
  {
    key: "WECHAT_PROJECT_ACCEPTANCE_PAGE",
    groupCode: "wechat",
    name: "微信项目验收详情页路径",
    description: "短信拉起小程序后进入的客户项目验收详情页路径。",
    valueType: "string",
    envNames: ["WECHAT_PROJECT_ACCEPTANCE_PAGE"],
    defaultValue: "packageCustomerPortal/pages/customer-project-acceptance/index",
  },
  {
    key: "WECHAT_MINIPROGRAM_ENV_VERSION",
    groupCode: "wechat",
    name: "微信小程序版本环境",
    description: "可在页面选择正式版、体验版或开发版。",
    valueType: "string",
    envNames: ["WECHAT_MINIPROGRAM_ENV_VERSION"],
    defaultValue: "release",
  },
  {
    key: "WECHAT_PARTNER_ONBOARDING_PAGE",
    groupCode: "wechat",
    name: "合伙人扫码入驻页路径",
    description: "城市合伙人专属小程序码进入的小程序页面路径。",
    valueType: "string",
    envNames: ["WECHAT_PARTNER_ONBOARDING_PAGE"],
    defaultValue: "pages/visitor/index",
  },
  {
    key: "WECHAT_MINIPROGRAM_QRCODE_CHECK_PATH",
    groupCode: "wechat",
    name: "微信小程序码校验页面路径",
    description: "生成城市合伙人专属小程序码时是否校验 page 已发布存在。",
    valueType: "boolean",
    envNames: ["WECHAT_MINIPROGRAM_QRCODE_CHECK_PATH"],
    defaultValue: "true",
  },
  {
    key: "CUSTOMER_LOG_SHARE_TARGET_ASSIST_COUNT",
    groupCode: "wechat",
    name: "助力目标人数",
    description: "客户日志分享活动目标助力人数。",
    valueType: "number",
    envNames: ["CUSTOMER_LOG_SHARE_TARGET_ASSIST_COUNT"],
    defaultValue: "10",
  },
  {
    key: "DEPLOY_NOTIFY_TO",
    groupCode: "notify",
    name: "部署通知收件人",
    description: "部署通知邮件收件人。",
    valueType: "string",
    envNames: ["DEPLOY_NOTIFY_TO"],
  },
  {
    key: "DEPLOY_NOTIFY_FROM",
    groupCode: "notify",
    name: "部署通知发件人",
    description: "部署通知邮件发件人。",
    valueType: "string",
    envNames: ["DEPLOY_NOTIFY_FROM"],
  },
  {
    key: "SMTP_HOST",
    groupCode: "notify",
    name: "SMTP 主机",
    description: "SMTP 服务器地址。",
    valueType: "string",
    envNames: ["SMTP_HOST"],
  },
  {
    key: "SMTP_USER",
    groupCode: "notify",
    name: "SMTP 用户名",
    description: "SMTP 登录用户名，加密存储。",
    valueType: "string",
    envNames: ["SMTP_USER"],
    isSecret: true,
  },
  {
    key: "SMTP_PASS",
    groupCode: "notify",
    name: "SMTP 密码/授权码",
    description: "SMTP 登录密码或授权码，加密存储。",
    valueType: "string",
    envNames: ["SMTP_PASS"],
    isSecret: true,
  },
  {
    key: "SMTP_PORT",
    groupCode: "notify",
    name: "SMTP 端口",
    description: "SMTP 服务器端口。",
    valueType: "number",
    envNames: ["SMTP_PORT"],
    defaultValue: "465",
  },
  {
    key: "SMTP_SECURE",
    groupCode: "notify",
    name: "SMTP 加密连接",
    description: "是否使用 SMTP 加密连接。",
    valueType: "boolean",
    envNames: ["SMTP_SECURE"],
    defaultValue: "true",
  },
  {
    key: "SMTP_FAMILY",
    groupCode: "notify",
    name: "SMTP 网络协议族",
    description: "SMTP 网络协议族，通常为 4 或 6。",
    valueType: "number",
    envNames: ["SMTP_FAMILY"],
  },

];
