import type { SettingDefinition } from './shared';

export const DEFINITIONS_AI_SOCIAL: SettingDefinition[] = [  {
    key: "AI_CHAT_COMPLETIONS_URL",
    groupCode: "ai",
    name: "AI 对话接口地址",
    description: "兼容 Chat Completions 的接口地址。",
    valueType: "string",
    envNames: ["AI_CHAT_COMPLETIONS_URL", "DEEPSEEK_CHAT_COMPLETIONS_URL"],
  },
  {
    key: "AI_API_KEY",
    groupCode: "ai",
    name: "AI 接口密钥",
    description: "OpenAI/OpenRouter 兼容接口密钥，加密存储。",
    valueType: "string",
    envNames: ["AI_API_KEY"],
    isSecret: true,
  },
  {
    key: "DEEPSEEK_API_KEY",
    groupCode: "ai",
    name: "DeepSeek 接口密钥",
    description: "DeepSeek 接口密钥，加密存储。",
    valueType: "string",
    envNames: ["DEEPSEEK_API_KEY"],
    isSecret: true,
  },
  {
    key: "AI_MODEL",
    groupCode: "ai",
    name: "AI 模型名称",
    description: "默认 AI 模型名称。",
    valueType: "string",
    envNames: ["AI_MODEL", "DEEPSEEK_MODEL"],
  },
  {
    key: "AI_REQUEST_TIMEOUT_MS",
    groupCode: "ai",
    name: "AI 请求超时时间",
    description: "AI 请求超时时间，单位毫秒。",
    valueType: "number",
    envNames: ["AI_REQUEST_TIMEOUT_MS"],
    defaultValue: "60000",
  },
  {
    key: "DECORATION_QA_SYSTEM_PROMPT",
    groupCode: "ai",
    name: "装修问答系统提示词",
    description: "装修问答功能使用的系统提示词。",
    valueType: "string",
    envNames: ["DECORATION_QA_SYSTEM_PROMPT"],
  },
  {
    key: "OPENROUTER_HTTP_REFERER",
    groupCode: "ai",
    name: "OpenRouter 来源标识",
    description: "OpenRouter 请求头中的来源标识。",
    valueType: "string",
    envNames: ["OPENROUTER_HTTP_REFERER"],
    defaultValue: "https://gooes.local",
  },
  {
    key: "OPENROUTER_APP_NAME",
    groupCode: "ai",
    name: "OpenRouter 应用名",
    description: "OpenRouter 请求头 X-Title。",
    valueType: "string",
    envNames: ["OPENROUTER_APP_NAME"],
    defaultValue: "gooes-decoration-qa",
  },
  {
    key: "SOCIAL_VIDEO_TRANSCRIPTION_ENABLED",
    groupCode: "social_video",
    name: "短视频语音识别开关",
    description: "是否启用小程序抖音链接语音转文本能力。",
    valueType: "boolean",
    envNames: ["SOCIAL_VIDEO_TRANSCRIPTION_ENABLED"],
    defaultValue: "true",
  },
  {
    key: "SOCIAL_VIDEO_TRANSCRIPTION_PROVIDER",
    groupCode: "social_video",
    name: "短视频识别主链路",
    description: "腾讯云语音识别链路会先使用 Apify 解析音视频地址；Apify 直接转写链路由 Apify 完成识别。",
    valueType: "string",
    envNames: ["SOCIAL_VIDEO_TRANSCRIPTION_PROVIDER"],
    defaultValue: "tencent_asr",
  },
  {
    key: "APIFY_API_TOKEN",
    groupCode: "social_video",
    name: "Apify 接口令牌",
    description: "Apify 接口令牌，加密存储。",
    valueType: "string",
    envNames: ["APIFY_API_TOKEN"],
    isSecret: true,
  },
  {
    key: "APIFY_TRANSCRIPT_ACTOR_ID",
    groupCode: "social_video",
    name: "Apify 转写运行器编号",
    description: "用于抖音视频转文本的 Apify 运行器编号。默认 apple_yang/douyin-transcripts-scraper。",
    valueType: "string",
    envNames: ["APIFY_TRANSCRIPT_ACTOR_ID"],
    defaultValue: "apple_yang/douyin-transcripts-scraper",
  },
  {
    key: "APIFY_TRANSCRIPT_TIMEOUT_MS",
    groupCode: "social_video",
    name: "Apify 转写超时",
    description: "调用 Apify 运行器的最大等待时间，单位毫秒。",
    valueType: "number",
    envNames: ["APIFY_TRANSCRIPT_TIMEOUT_MS"],
    defaultValue: "60000",
  },
  {
    key: "SOCIAL_VIDEO_CACHE_TTL_HOURS",
    groupCode: "social_video",
    name: "短视频识别缓存时间",
    description: "同一抖音链接识别成功后复用结果的小时数。",
    valueType: "number",
    envNames: ["SOCIAL_VIDEO_CACHE_TTL_HOURS"],
    defaultValue: "24",
  },
  {
    key: "SOCIAL_VIDEO_DAILY_LIMIT_PER_USER",
    groupCode: "social_video",
    name: "单用户每日识别上限",
    description: "单个登录用户每天最多可创建的短视频识别任务数。",
    valueType: "number",
    envNames: ["SOCIAL_VIDEO_DAILY_LIMIT_PER_USER"],
    defaultValue: "20",
  },
  {
    key: "SOCIAL_VIDEO_CONCURRENCY_LIMIT",
    groupCode: "social_video",
    name: "短视频识别并发数",
    description: "短视频识别后台任务同时执行下载、音频提取和语音识别的最大任务数，建议 1-2。",
    valueType: "number",
    envNames: ["SOCIAL_VIDEO_CONCURRENCY_LIMIT"],
    defaultValue: "1",
  },
  {
    key: "SOCIAL_VIDEO_WORKER_POLL_INTERVAL_MS",
    groupCode: "social_video",
    name: "短视频识别后台轮询间隔",
    description: "后台任务扫描待处理任务的间隔时间，单位毫秒。",
    valueType: "number",
    envNames: ["SOCIAL_VIDEO_WORKER_POLL_INTERVAL_MS"],
    defaultValue: "3000",
  },
  {
    key: "SOCIAL_VIDEO_STALE_TASK_TIMEOUT_MS",
    groupCode: "social_video",
    name: "短视频识别任务超时回收",
    description: "后台任务重启或崩溃后，处理中任务超过该时间未更新则允许重新领取，单位毫秒。",
    valueType: "number",
    envNames: ["SOCIAL_VIDEO_STALE_TASK_TIMEOUT_MS"],
    defaultValue: "900000",
  },
  {
    key: "SOCIAL_VIDEO_SCRIPT_DAILY_LIMIT_PER_USER",
    groupCode: "social_video",
    name: "短视频脚本每日生成上限",
    description: "单个登录用户每天最多生成的短视频拍摄脚本数量。",
    valueType: "number",
    envNames: ["SOCIAL_VIDEO_SCRIPT_DAILY_LIMIT_PER_USER"],
    defaultValue: "20",
  },
  {
    key: "SOCIAL_VIDEO_SCRIPT_CACHE_TTL_HOURS",
    groupCode: "social_video",
    name: "短视频脚本缓存时间",
    description: "同一转写任务、目标平台、风格、时长和目标生成成功后复用结果的小时数。",
    valueType: "number",
    envNames: ["SOCIAL_VIDEO_SCRIPT_CACHE_TTL_HOURS"],
    defaultValue: "24",
  },
  {
    key: "SOCIAL_VIDEO_SCRIPT_AI_MODEL",
    groupCode: "social_video",
    name: "短视频脚本 AI 模型",
    description: "短视频脚本生成优先使用的 AI 模型；为空时使用 AI_MODEL。",
    valueType: "string",
    envNames: ["SOCIAL_VIDEO_SCRIPT_AI_MODEL"],
  },
  {
    key: "SOCIAL_VIDEO_SCRIPT_AI_TIMEOUT_MS",
    groupCode: "social_video",
    name: "短视频脚本 AI 超时",
    description: "短视频脚本同步生成接口的 AI 请求超时时间，单位毫秒。",
    valueType: "number",
    envNames: ["SOCIAL_VIDEO_SCRIPT_AI_TIMEOUT_MS"],
    defaultValue: "25000",
  },
  {
    key: "SOCIAL_VIDEO_SCRIPT_SOURCE_MAX_CHARS",
    groupCode: "social_video",
    name: "短视频脚本输入文本上限",
    description: "发送给 AI 的转写文本最大字符数。",
    valueType: "number",
    envNames: ["SOCIAL_VIDEO_SCRIPT_SOURCE_MAX_CHARS"],
    defaultValue: "4000",
  },
  {
    key: "SOCIAL_VIDEO_MAX_DURATION_SECONDS",
    groupCode: "social_video",
    name: "短视频最大时长",
    description: "短视频语音识别建议最大视频时长，单位秒。Apify 直接转写路径中作为配置和后续兜底限制。",
    valueType: "number",
    envNames: ["SOCIAL_VIDEO_MAX_DURATION_SECONDS"],
    defaultValue: "600",
  },
  {
    key: "SOCIAL_VIDEO_MAX_DOWNLOAD_BYTES",
    groupCode: "social_video",
    name: "短视频下载大小上限",
    description: "从解析地址下载媒体文件的最大字节数。",
    valueType: "number",
    envNames: ["SOCIAL_VIDEO_MAX_DOWNLOAD_BYTES"],
    defaultValue: "104857600",
  },
  {
    key: "SOCIAL_VIDEO_DOWNLOAD_TIMEOUT_MS",
    groupCode: "social_video",
    name: "短视频下载超时",
    description: "下载抖音音视频文件的超时时间，单位毫秒。",
    valueType: "number",
    envNames: ["SOCIAL_VIDEO_DOWNLOAD_TIMEOUT_MS"],
    defaultValue: "180000",
  },
  {
    key: "SOCIAL_VIDEO_FFMPEG_TIMEOUT_MS",
    groupCode: "social_video",
    name: "音频提取超时",
    description: "从短视频提取音频的超时时间，单位毫秒。",
    valueType: "number",
    envNames: ["SOCIAL_VIDEO_FFMPEG_TIMEOUT_MS"],
    defaultValue: "120000",
  },
  {
    key: "SOCIAL_VIDEO_AUDIO_BITRATE",
    groupCode: "social_video",
    name: "语音识别音频码率",
    description: "提交腾讯云语音识别前生成音频的目标码率，建议 32k。",
    valueType: "string",
    envNames: ["SOCIAL_VIDEO_AUDIO_BITRATE"],
    defaultValue: "32k",
  },
  {
    key: "TENCENT_ASR_REGION",
    groupCode: "social_video",
    name: "腾讯云语音识别区域",
    description: "腾讯云语音识别接口区域。",
    valueType: "string",
    envNames: ["TENCENT_ASR_REGION"],
    defaultValue: "ap-shanghai",
  },
  {
    key: "TENCENT_ASR_ENDPOINT",
    groupCode: "social_video",
    name: "腾讯云语音识别接口域名",
    description: "腾讯云语音识别接口域名。",
    valueType: "string",
    envNames: ["TENCENT_ASR_ENDPOINT"],
    defaultValue: "asr.tencentcloudapi.com",
  },
  {
    key: "TENCENT_ASR_ENGINE_MODEL_TYPE",
    groupCode: "social_video",
    name: "腾讯云语音识别引擎",
    description: "录音文件识别引擎，中文短视频建议 16k_zh。",
    valueType: "string",
    envNames: ["TENCENT_ASR_ENGINE_MODEL_TYPE"],
    defaultValue: "16k_zh",
  },
  {
    key: "TENCENT_ASR_RES_TEXT_FORMAT",
    groupCode: "social_video",
    name: "腾讯云语音识别返回格式",
    description: "录音文件识别返回样式，3 为带标点并按标点分段，适合字幕/短视频文案。",
    valueType: "number",
    envNames: ["TENCENT_ASR_RES_TEXT_FORMAT"],
    defaultValue: "3",
  },
  {
    key: "TENCENT_ASR_POLL_TIMEOUT_MS",
    groupCode: "social_video",
    name: "腾讯云语音识别轮询超时",
    description: "提交录音识别任务后等待结果的最大时间，单位毫秒。",
    valueType: "number",
    envNames: ["TENCENT_ASR_POLL_TIMEOUT_MS"],
    defaultValue: "180000",
  },

];
