import { DEFINITIONS_SMS } from './definitions-sms';
import { DEFINITIONS_INTEGRATIONS } from './definitions-integrations';
import { DEFINITIONS_AI_SOCIAL } from './definitions-ai-social';
import { DEFINITIONS_WECHAT_NOTIFY } from './definitions-wechat-notify';
import { DEFINITIONS_PICTURE_LIBRARY } from './definitions-picture-library';
import { DEFINITIONS_VISITOR } from './definitions-visitor';
import type { SettingDefinition } from './shared';

export const SETTING_DEFINITIONS: SettingDefinition[] = [
  ...DEFINITIONS_SMS,
  ...DEFINITIONS_INTEGRATIONS,
  ...DEFINITIONS_AI_SOCIAL,
  ...DEFINITIONS_WECHAT_NOTIFY,
  ...DEFINITIONS_PICTURE_LIBRARY,
  ...DEFINITIONS_VISITOR,
];

export const definitionByKey = new Map(SETTING_DEFINITIONS.map((item) => [item.key, item]));

export const TENANT_SMS_CHANNEL_MODE_KEY = "SMS_CHANNEL_MODE";
export const TENANT_SMS_PLATFORM_MODE = "platform";
export const TENANT_SMS_ALIYUN_MODE = "tenant_aliyun";
export const TENANT_SMS_TENCENT_MODE = "tenant_tencent";

export const TENANT_SMS_BASE_SETTING_KEYS = new Set([
  TENANT_SMS_CHANNEL_MODE_KEY,
]);

export const TENANT_ALIYUN_SMS_SETTING_KEYS = new Set([
  "ALIBABA_CLOUD_ACCESS_KEY_ID",
  "ALIBABA_CLOUD_ACCESS_KEY_SECRET",
  "ALIYUN_SMS_SIGN_NAME",
  "ALIYUN_SMS_TEMPLATE_CODE_BIND_CUSTOMER",
  "ALIYUN_SMS_TEMPLATE_CODE_BIND_EMPLOYEE",
  "ALIYUN_SMS_TEMPLATE_CODE_ADMIN_LOGIN",
  "ALIYUN_SMS_TEMPLATE_CODE_PROJECT_ACCEPTANCE",
  "PROJECT_ACCEPTANCE_SMS_EXPIRE_HOURS",
]);

export const TENANT_TENCENT_SMS_SETTING_KEYS = new Set([
  "TENCENT_SMS_SECRET_ID",
  "TENCENT_SMS_SECRET_KEY",
  "TENCENT_SMS_REGION",
  "TENCENT_SMS_ENDPOINT",
  "TENCENT_SMS_SDK_APP_ID",
  "TENCENT_SMS_SIGN_NAME",
  "TENCENT_SMS_TEMPLATE_ID_BIND_CUSTOMER",
  "TENCENT_SMS_TEMPLATE_ID_BIND_EMPLOYEE",
  "TENCENT_SMS_TEMPLATE_ID_ADMIN_LOGIN",
  "TENCENT_SMS_TEMPLATE_ID_PROJECT_ACCEPTANCE",
  "PROJECT_ACCEPTANCE_SMS_EXPIRE_HOURS",
]);

export const TENANT_CUSTOMER_SERVICE_SETTING_KEYS = new Set([
  "CUSTOMER_SERVICE_ENABLED",
  "CUSTOMER_SERVICE_PHONE",
  "CUSTOMER_SERVICE_WORKING_HOURS",
  "CUSTOMER_SERVICE_NOTICE",
]);

export const TENANT_VISITOR_SETTING_KEYS = new Set([
  "VISITOR_PROJECT_CONSULTATION_ENABLED",
]);

export const TENANT_OVERRIDABLE_SETTING_KEYS = new Set([
  ...TENANT_SMS_BASE_SETTING_KEYS,
  ...TENANT_ALIYUN_SMS_SETTING_KEYS,
  ...TENANT_TENCENT_SMS_SETTING_KEYS,
  ...TENANT_CUSTOMER_SERVICE_SETTING_KEYS,
  ...TENANT_VISITOR_SETTING_KEYS,
]);

export const TENANT_SETTING_KEYS_HIDE_PLATFORM_VALUE = new Set([
  ...TENANT_ALIYUN_SMS_SETTING_KEYS,
  ...TENANT_TENCENT_SMS_SETTING_KEYS,
]);

export const LEGACY_PARTIAL_TENANT_SMS_SETTING_KEYS = new Set([
  "ALIBABA_CLOUD_ACCESS_KEY_ID",
  "ALIBABA_CLOUD_ACCESS_KEY_SECRET",
  "ALIYUN_SMS_SIGN_NAME",
  "ALIYUN_SMS_TEMPLATE_CODE_BIND_CUSTOMER",
  "ALIYUN_SMS_TEMPLATE_CODE_BIND_EMPLOYEE",
  "ALIYUN_SMS_TEMPLATE_CODE_ADMIN_LOGIN",
  "ALIYUN_SMS_TEMPLATE_CODE_PROJECT_ACCEPTANCE",
  "TENCENT_SMS_SECRET_ID",
  "TENCENT_SMS_SECRET_KEY",
  "TENCENT_SMS_REGION",
  "TENCENT_SMS_ENDPOINT",
  "TENCENT_SMS_SDK_APP_ID",
  "TENCENT_SMS_SIGN_NAME",
  "TENCENT_SMS_TEMPLATE_ID_BIND_CUSTOMER",
  "TENCENT_SMS_TEMPLATE_ID_BIND_EMPLOYEE",
  "TENCENT_SMS_TEMPLATE_ID_ADMIN_LOGIN",
  "TENCENT_SMS_TEMPLATE_ID_PROJECT_ACCEPTANCE",
  "PROJECT_ACCEPTANCE_SMS_EXPIRE_HOURS",
]);
