import type { SettingDefinition } from './shared';

export const DEFINITIONS_INTEGRATIONS: SettingDefinition[] = [  {
    key: "CUSTOMER_SERVICE_ENABLED",
    groupCode: "customer_service",
    name: "客服入口开关",
    description: "控制微信小程序客户侧是否展示客服入口并允许提交客服问题。",
    valueType: "boolean",
    envNames: ["CUSTOMER_SERVICE_ENABLED"],
    defaultValue: "false",
  },
  {
    key: "TENCENT_OCR_ENABLED",
    groupCode: "ocr",
    name: "启用腾讯云 OCR",
    description: "控制平台统一证照识别服务是否可用。",
    valueType: "boolean",
    envNames: ["TENCENT_OCR_ENABLED"],
    defaultValue: "false",
  },
  {
    key: "TENCENT_OCR_SECRET_ID",
    groupCode: "ocr",
    name: "腾讯云 OCR 密钥编号",
    description: "证照识别专用访问密钥编号，加密存储。",
    valueType: "string",
    envNames: ["TENCENT_OCR_SECRET_ID"],
    isSecret: true,
  },
  {
    key: "TENCENT_OCR_SECRET_KEY",
    groupCode: "ocr",
    name: "腾讯云 OCR 密钥",
    description: "证照识别专用访问密钥，加密存储。",
    valueType: "string",
    envNames: ["TENCENT_OCR_SECRET_KEY"],
    isSecret: true,
  },
  {
    key: "TENCENT_OCR_REGION",
    groupCode: "ocr",
    name: "腾讯云 OCR 区域",
    description: "证照识别接口使用的腾讯云区域。",
    valueType: "string",
    envNames: ["TENCENT_OCR_REGION"],
    defaultValue: "ap-guangzhou",
  },
  {
    key: "TENCENT_OCR_ENDPOINT",
    groupCode: "ocr",
    name: "腾讯云 OCR 接口域名",
    description: "证照识别服务请求使用的接口域名。",
    valueType: "string",
    envNames: ["TENCENT_OCR_ENDPOINT"],
    defaultValue: "ocr.tencentcloudapi.com",
  },
  {
    key: "TENCENT_OCR_REQUEST_TIMEOUT_MS",
    groupCode: "ocr",
    name: "腾讯云 OCR 请求超时",
    description: "单次证照识别请求的超时时间，单位毫秒。",
    valueType: "number",
    envNames: ["TENCENT_OCR_REQUEST_TIMEOUT_MS"],
    defaultValue: "10000",
  },
  {
    key: "TENCENT_OCR_DEFAULT_TENANT_DAILY_LIMIT",
    groupCode: "ocr",
    name: "租户每日识别额度",
    description: "每个租户每天允许发起的证照识别次数。",
    valueType: "number",
    envNames: ["TENCENT_OCR_DEFAULT_TENANT_DAILY_LIMIT"],
    defaultValue: "100",
  },
  {
    key: "TENCENT_OCR_RESULT_TTL_HOURS",
    groupCode: "ocr",
    name: "识别结果保留时长",
    description: "敏感识别结果密文的可读保留时间，单位小时。",
    valueType: "number",
    envNames: ["TENCENT_OCR_RESULT_TTL_HOURS"],
    defaultValue: "24",
  },
  {
    key: "TENCENT_OCR_ID_CARD_ENCRYPTED_ENABLED",
    groupCode: "ocr",
    name: "启用身份证加密识别",
    description: "仅在加密材料验证完成后开放身份证识别能力。",
    valueType: "boolean",
    envNames: ["TENCENT_OCR_ID_CARD_ENCRYPTED_ENABLED"],
    defaultValue: "true",
  },
  {
    key: "TENCENT_OCR_ENCRYPTION_PUBLIC_KEY_PEM",
    groupCode: "ocr",
    name: "身份证识别加密公钥",
    description: "腾讯云证照识别提供的身份证请求加密公钥，加密存储。",
    valueType: "string",
    envNames: ["TENCENT_OCR_ENCRYPTION_PUBLIC_KEY_PEM"],
    isSecret: true,
  },
  {
    key: "TENCENT_OCR_ENCRYPTION_ALGORITHM",
    groupCode: "ocr",
    name: "身份证识别加密算法",
    description: "身份证敏感数据传输使用的加密算法。",
    valueType: "string",
    envNames: ["TENCENT_OCR_ENCRYPTION_ALGORITHM"],
    defaultValue: "AES-256-CBC",
  },
  {
    key: "CUSTOMER_SERVICE_PHONE",
    groupCode: "customer_service",
    name: "客服电话",
    description: "客户侧一键拨打的客服电话，按租户配置。",
    valueType: "string",
    envNames: ["CUSTOMER_SERVICE_PHONE"],
  },
  {
    key: "CUSTOMER_SERVICE_WORKING_HOURS",
    groupCode: "customer_service",
    name: "客服工作时间",
    description: "客户侧展示的客服工作时间文案。示例：周一至周日 09:00-18:00。",
    valueType: "string",
    envNames: ["CUSTOMER_SERVICE_WORKING_HOURS"],
  },
  {
    key: "CUSTOMER_SERVICE_NOTICE",
    groupCode: "customer_service",
    name: "客服提示文案",
    description: "客户侧客服入口展示的说明文案。",
    valueType: "string",
    envNames: ["CUSTOMER_SERVICE_NOTICE"],
  },
  {
    key: "EZVIZ_API_BASE_URL",
    groupCode: "ezviz",
    name: "萤石开放平台地址",
    description: "萤石云开放平台接口基础地址。",
    valueType: "string",
    envNames: ["EZVIZ_API_BASE_URL"],
    defaultValue: "https://open.ys7.com",
  },
  {
    key: "EZVIZ_APP_KEY",
    groupCode: "ezviz",
    name: "萤石应用密钥编号",
    description: "萤石开放平台应用密钥编号，加密存储。",
    valueType: "string",
    envNames: ["EZVIZ_APP_KEY"],
    isSecret: true,
  },
  {
    key: "EZVIZ_APP_SECRET",
    groupCode: "ezviz",
    name: "萤石应用密钥",
    description: "萤石开放平台应用密钥，加密存储。",
    valueType: "string",
    envNames: ["EZVIZ_APP_SECRET"],
    isSecret: true,
  },
  {
    key: "EZVIZ_TOKEN_REFRESH_AHEAD_MS",
    groupCode: "ezviz",
    name: "萤石访问令牌提前刷新时间",
    description: "访问令牌过期前提前刷新的毫秒数。",
    valueType: "number",
    envNames: ["EZVIZ_TOKEN_REFRESH_AHEAD_MS"],
    defaultValue: String(10 * 60 * 1000),
  },
  {
    key: "EZPLAYER_PLUGIN_VERSION",
    groupCode: "ezviz",
    name: "EZPlayer 插件版本",
    description: "前端播放器使用的 EZPlayer 插件版本。",
    valueType: "string",
    envNames: ["EZPLAYER_PLUGIN_VERSION"],
    defaultValue: "1.5.2",
  },
  {
    key: "TENCENTCLOUD_SECRET_ID",
    groupCode: "tencent_iot_video",
    name: "腾讯云密钥编号",
    description: "腾讯云物联网智能视频服务（行业版）密钥编号，加密存储。",
    valueType: "string",
    envNames: ["TENCENTCLOUD_SECRET_ID"],
    isSecret: true,
  },
  {
    key: "TENCENTCLOUD_SECRET_KEY",
    groupCode: "tencent_iot_video",
    name: "腾讯云密钥",
    description: "腾讯云物联网智能视频服务（行业版）密钥，加密存储。",
    valueType: "string",
    envNames: ["TENCENTCLOUD_SECRET_KEY"],
    isSecret: true,
  },
  {
    key: "TENCENT_IOT_VIDEO_REGION",
    groupCode: "tencent_iot_video",
    name: "腾讯云区域",
    description: "物联网智能视频服务（行业版）接口区域。",
    valueType: "string",
    envNames: ["TENCENT_IOT_VIDEO_REGION"],
    defaultValue: "ap-guangzhou",
  },
  {
    key: "TENCENT_IOT_VIDEO_ENDPOINT",
    groupCode: "tencent_iot_video",
    name: "腾讯云接口域名",
    description: "物联网智能视频服务（行业版）接口域名。",
    valueType: "string",
    envNames: ["TENCENT_IOT_VIDEO_ENDPOINT"],
    defaultValue: "iotvideoindustry.tencentcloudapi.com",
  },
  {
    key: "TENCENT_IOT_VIDEO_DEFAULT_PROTOCOL",
    groupCode: "tencent_iot_video",
    name: "腾讯云默认播放协议",
    description: "小程序播放优先使用协议，建议 flv。",
    valueType: "string",
    envNames: ["TENCENT_IOT_VIDEO_DEFAULT_PROTOCOL"],
    defaultValue: "flv",
  },
  {
    key: "TENCENT_IOT_VIDEO_LIVE_STREAM_ACTION",
    groupCode: "tencent_iot_video",
    name: "腾讯云实时地址接口",
    description: "默认使用新版 DescribeChannelLiveStreamURL；异常时后端会尝试旧接口兜底。",
    valueType: "string",
    envNames: ["TENCENT_IOT_VIDEO_LIVE_STREAM_ACTION"],
    defaultValue: "DescribeChannelLiveStreamURL",
  },
  {
    key: "TENCENT_LBS_WEBSERVICE_KEY",
    groupCode: "tencent_lbs",
    name: "腾讯位置服务端密钥",
    description: "后端调用腾讯位置服务接口使用的密钥，例如行政区划、逆地址解析等接口。",
    valueType: "string",
    envNames: ["TENCENT_LBS_WEBSERVICE_KEY", "TENCENT_LBS_KEY"],
  },
  {
    key: "TENCENT_LBS_WEBSERVICE_SK",
    groupCode: "tencent_lbs",
    name: "腾讯位置签名校验密钥",
    description: "腾讯位置服务接口开启签名校验后用于计算签名的密钥，加密存储。",
    valueType: "string",
    envNames: ["TENCENT_LBS_WEBSERVICE_SK", "TENCENT_LBS_SK"],
    isSecret: true,
  },
  {
    key: "TENCENT_LBS_MINIPROGRAM_KEY",
    groupCode: "tencent_lbs",
    name: "腾讯位置小程序密钥",
    description: "微信小程序端腾讯位置服务使用的密钥，用于定位、逆地址解析等小程序侧能力。",
    valueType: "string",
    envNames: ["TENCENT_LBS_MINIPROGRAM_KEY", "TENCENT_MAP_MINIPROGRAM_KEY"],
  },
  {
    key: "TENCENT_LBS_WEB_JS_KEY",
    groupCode: "tencent_lbs",
    name: "腾讯位置后台浏览器密钥",
    description: "后台浏览器端腾讯地图使用的密钥，需在腾讯位置服务控制台配置来源白名单。",
    valueType: "string",
    envNames: ["TENCENT_LBS_WEB_JS_KEY", "TENCENT_MAP_WEB_JS_KEY"],
  },
  {
    key: "LOCATION_MATCH_ENABLED",
    groupCode: "location",
    name: "定位匹配开关",
    description: "控制小程序登录后是否启用定位匹配装修公司能力。",
    valueType: "boolean",
    envNames: ["LOCATION_MATCH_ENABLED"],
    defaultValue: "true",
  },
  {
    key: "LOCATION_CONTEXT_TTL_HOURS",
    groupCode: "location",
    name: "定位上下文有效期",
    description: "用户定位匹配上下文的有效期，单位小时。",
    valueType: "number",
    envNames: ["LOCATION_CONTEXT_TTL_HOURS"],
    defaultValue: "24",
  },
  {
    key: "LOCATION_STORE_RAW_COORDINATE",
    groupCode: "location",
    name: "保存原始定位坐标",
    description: "控制是否长期保存用户原始经纬度；默认关闭，仅保存行政区和匹配结果。",
    valueType: "boolean",
    envNames: ["LOCATION_STORE_RAW_COORDINATE"],
    defaultValue: "false",
  },
  {
    key: "PLATFORM_STORAGE_PROVIDER",
    groupCode: "storage",
    name: "平台存储提供商",
    description: "平台通用图片和附件上传的存储提供商，可选择旧版对象存储或腾讯云对象存储。",
    valueType: "string",
    envNames: ["PLATFORM_STORAGE_PROVIDER"],
    defaultValue: "supabase_storage",
  },
  {
    key: "TENCENT_COS_SECRET_ID",
    groupCode: "storage",
    name: "腾讯云对象存储密钥编号",
    description: "腾讯云对象存储专用密钥编号，加密存储。与物联网视频、语音识别等腾讯云密钥解耦。",
    valueType: "string",
    envNames: ["TENCENT_COS_SECRET_ID"],
    isSecret: true,
  },
  {
    key: "TENCENT_COS_SECRET_KEY",
    groupCode: "storage",
    name: "腾讯云对象存储密钥",
    description: "腾讯云对象存储专用密钥，加密存储。与物联网视频、语音识别等腾讯云密钥解耦。",
    valueType: "string",
    envNames: ["TENCENT_COS_SECRET_KEY"],
    isSecret: true,
  },
  {
    key: "PLATFORM_COS_BUCKET",
    groupCode: "storage",
    name: "平台对象存储桶",
    description: "平台通用图片和附件存储使用的腾讯云对象存储桶名称，需包含应用编号后缀。",
    valueType: "string",
    envNames: ["PLATFORM_COS_BUCKET"],
  },
  {
    key: "PLATFORM_COS_REGION",
    groupCode: "storage",
    name: "平台对象存储区域",
    description: "平台对象存储桶所在区域，例如 ap-guangzhou。",
    valueType: "string",
    envNames: ["PLATFORM_COS_REGION"],
    defaultValue: "ap-guangzhou",
  },
  {
    key: "PLATFORM_COS_PUBLIC_BASE_URL",
    groupCode: "storage",
    name: "平台文件访问域名",
    description: "平台文件公网或加速访问域名，例如 https://assets.goodcms.cn。为空时后端返回对象存储签名链接。",
    valueType: "string",
    envNames: ["PLATFORM_COS_PUBLIC_BASE_URL"],
  },
  {
    key: "PLATFORM_COS_SIGNED_URL_TTL_SECONDS",
    groupCode: "storage",
    name: "对象存储签名链接有效期",
    description: "未配置公网或加速访问域名时，后端生成对象存储签名链接的有效期，单位秒。",
    valueType: "number",
    envNames: ["PLATFORM_COS_SIGNED_URL_TTL_SECONDS"],
    defaultValue: "900",
  },
  {
    key: "PLATFORM_COS_UPLOAD_USE_ACCELERATE",
    groupCode: "storage",
    name: "对象存储上传使用全球加速",
    description: "开启后直传上传链接使用腾讯云对象存储全球加速域名。需先在腾讯云对象存储桶启用全球加速并配置跨域规则。",
    valueType: "boolean",
    envNames: ["PLATFORM_COS_UPLOAD_USE_ACCELERATE"],
    defaultValue: "false",
  },
  {
    key: "PLATFORM_FILE_ACCESS_POLICY",
    groupCode: "storage",
    name: "平台文件访问策略",
    description: "按业务场景控制文件访问模式和签名链接有效期。访问模式支持公开链接和签名链接，签名有效期单位秒。",
    valueType: "json",
    envNames: ["PLATFORM_FILE_ACCESS_POLICY"],
    defaultValue: JSON.stringify({
      default: {
        access_mode: "signed",
        signed_url_ttl_seconds: 1800,
      },
      scenes: {
        project_log: {
          access_mode: "signed",
          signed_url_ttl_seconds: 1800,
        },
        project_log_comment: {
          access_mode: "signed",
          signed_url_ttl_seconds: 1800,
        },
        project_acceptance: {
          access_mode: "signed",
          signed_url_ttl_seconds: 1800,
        },
        customer_follow_up_comment: {
          access_mode: "signed",
          signed_url_ttl_seconds: 1800,
        },
        customer_service: {
          access_mode: "signed",
          signed_url_ttl_seconds: 1800,
        },
        customer_douyin_screenshot: {
          access_mode: "signed",
          signed_url_ttl_seconds: 1800,
        },
        expense_request: {
          access_mode: "signed",
          signed_url_ttl_seconds: 600,
        },
        expense_request_settlement: {
          access_mode: "signed",
          signed_url_ttl_seconds: 600,
        },
        referral_payment: {
          access_mode: "signed",
          signed_url_ttl_seconds: 600,
        },
        employee_avatar: {
          access_mode: "signed",
          signed_url_ttl_seconds: 21600,
        },
        customer_avatar: {
          access_mode: "signed",
          signed_url_ttl_seconds: 21600,
        },
        h5_marketing_page: {
          access_mode: "public",
          signed_url_ttl_seconds: 0,
        },
        panorama_tiles: {
          access_mode: "public",
          signed_url_ttl_seconds: 0,
        },
      },
    }, null, 2),
  },

];
