export * from "@gooes/domain";

export const BRANDING_VIRTUAL_PAYMENT_SESSION_REFRESH_REQUIRED =
  "BRANDING_VIRTUAL_PAYMENT_SESSION_REFRESH_REQUIRED" as const;

export const BRANDING_ADDON_PAYMENT_CHANNEL_MIGRATED =
  "BRANDING_ADDON_PAYMENT_CHANNEL_MIGRATED" as const;
