export const workflowDefinitionFixture = {
  id: "definition-1",
  tenant_id: "tenant-1",
  workflow_key: "construction_main",
  name: "工程主流程",
  description: null,
  category: "construction",
  status: "active",
  active_version_id: "version-1",
  created_by: null,
  updated_by: null,
  created_at: "2026-06-16T00:00:00.000Z",
  updated_at: "2026-06-16T00:00:00.000Z",
};

export const paymentGateGraphFixture = {
  definition: workflowDefinitionFixture,
  version: null,
  nodes: [
    {
      id: "node-plumbing",
      tenant_id: "tenant-1",
      definition_id: "definition-1",
      node_key: "procedure_plumbing_electrical",
      node_type: "procedure",
      business_kind: "procedure_template",
      title: "水电",
      description: null,
      position: { x: 0, y: 0 },
      config: {
        stage_key: "plumbing_electrical",
        require_log: true,
        min_image_count: 1,
        trigger_acceptance: true,
      },
      sort_order: 40,
      created_at: "2026-06-16T00:00:00.000Z",
      updated_at: "2026-06-16T00:00:00.000Z",
    },
    {
      id: "node-payment",
      tenant_id: "tenant-1",
      definition_id: "definition-1",
      node_key: "payment_stage_2",
      node_type: "confirmation",
      business_kind: "payment_collection",
      title: "中期进度款",
      description: null,
      position: { x: 0, y: 0 },
      config: { payment_type: "stage_2" },
      sort_order: 50,
      created_at: "2026-06-16T00:00:00.000Z",
      updated_at: "2026-06-16T00:00:00.000Z",
    },
    {
      id: "node-tiling",
      tenant_id: "tenant-1",
      definition_id: "definition-1",
      node_key: "procedure_tiling",
      node_type: "procedure",
      business_kind: "procedure_template",
      title: "瓦工",
      description: null,
      position: { x: 0, y: 0 },
      config: { stage_key: "tiling" },
      sort_order: 60,
      created_at: "2026-06-16T00:00:00.000Z",
      updated_at: "2026-06-16T00:00:00.000Z",
    },
  ],
  edges: [
    {
      id: "edge-payment-tiling",
      tenant_id: "tenant-1",
      definition_id: "definition-1",
      source_node_id: "node-payment",
      target_node_id: "node-tiling",
      label: "瓦工",
      condition: { operator: "always" },
      priority: 50,
      created_at: "2026-06-16T00:00:00.000Z",
      updated_at: "2026-06-16T00:00:00.000Z",
    },
  ],
};
