// src/errors/error-codes.ts

export const ErrorCodes = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  TOKEN_MISSING: "TOKEN_MISSING",
  TOKEN_INVALID: "TOKEN_INVALID",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  FORBIDDEN: "FORBIDDEN",
  DB_ERROR: "DB_ERROR",
  USER_EXISTS: "USER_EXISTS",
  NOT_AUTHENTICATED: "NOT_AUTHENTICATED",
  ALREADY_ASSISTED: "ALREADY_ASSISTED",
  OWNER_SELF_NOT_ALLOWED: "OWNER_SELF_NOT_ALLOWED",
  CAMPAIGN_ACHIEVED: "CAMPAIGN_ACHIEVED",
  REWARD_CLAIMED: "REWARD_CLAIMED",
  CAMPAIGN_CLOSED: "CAMPAIGN_CLOSED",
  RISK_BLOCKED: "RISK_BLOCKED",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
