import { PaginationQuerySchema } from "@/schema/request";
import { z } from "zod";

export const PlatformAuditLogActionSchema = z.enum([
  "tenant_create",
  "tenant_update",
  "tenant_suspend",
  "tenant_activate",
  "tenant_admin_create",
  "platform_lead_assign",
  "platform_device_access_view",
  "platform_device_sync",
  "platform_device_password_query",
  "platform_device_password_reset",
  "platform_device_cloud_delete",
  "platform_billing_recharge",
  "platform_billing_recharge_refund_approve",
  "platform_billing_recharge_refund_reject",
  "platform_billing_recharge_refund_execute",
  "platform_billing_pricing_update",
  "platform_config_update",
  "platform_release_dispatch",
  "platform_release_tag_create",
  "tenant_service_area_create",
  "tenant_service_area_update",
  "picture_category_create",
  "picture_category_update",
  "picture_category_disable",
  "picture_asset_create",
  "picture_asset_update",
  "picture_asset_published",
  "picture_asset_hidden",
  "picture_asset_draft",
  "picture_asset_delete",
  "picture_comment_hide",
  "picture_comment_show",
  "picture_comment_delete",
  "picture_health_comment_count_repair",
  "picture_health_category_cover_repair",
  "wechat_rebind_approve",
  "wechat_rebind_reject",
  "platform_partner_member_rebind_approve",
  "platform_partner_member_rebind_reject",
  "platform_partner_regions_update",
  "site_content_create",
  "site_content_publish",
  "site_content_rollback",
  "site_content_archive",
  "tenant_onboarding_submit",
  "tenant_onboarding_start_review",
  "tenant_onboarding_request_supplement",
  "tenant_onboarding_request_partner_assist",
  "tenant_onboarding_approve",
  "tenant_onboarding_reject",
  "tenant_onboarding_withdraw",
  "tenant_onboarding_partner_assist",
  "tenant_onboarding_notification_retry",
  "service_provider_submit_review",
  "service_provider_publish",
  "service_provider_return_draft",
  "service_provider_suspend",
  "platform_supplier_create",
  "platform_supplier_submit",
  "platform_supplier_approve",
  "platform_supplier_reject",
  "platform_supplier_suspend",
  "platform_supplier_resume",
  "platform_supplier_blacklist",
  "supplier_qualification_verify",
  "supplier_qualification_reject",
  "tenant_supplier_module_enable",
  "tenant_supplier_module_disable",
  "tenant_supplier_contract_policy_update",
  "tenant_supplier_create",
  "tenant_supplier_activate",
  "tenant_supplier_suspend",
  "tenant_supplier_terminate",
  "tenant_supplier_blacklist",
  "supplier_contract_activate",
  "supplier_contract_terminate",
  "branding_addon_product.update",
  "branding_virtual_product.validate",
  "branding_virtual_refund.create",
]);

export const PlatformAuditLogStatusSchema = z.enum(["success", "failure"]);

export const PlatformAuditLogListQuerySchema = PaginationQuerySchema.extend({
  action: PlatformAuditLogActionSchema.optional(),
  status: PlatformAuditLogStatusSchema.optional(),
  target_tenant_id: z.uuid("无效的租户 ID").optional(),
  resource_type: z.string().trim().max(80, "资源类型不能超过 80 个字符").optional(),
  resource_id: z.uuid("无效的资源 ID").optional(),
  keyword: z.string().trim().max(80, "关键词不能超过 80 个字符").optional(),
});

export type PlatformAuditLogAction = z.infer<typeof PlatformAuditLogActionSchema>;
export type PlatformAuditLogStatus = z.infer<typeof PlatformAuditLogStatusSchema>;
export type PlatformAuditLogListQuery = z.infer<typeof PlatformAuditLogListQuerySchema>;
