name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted    #使用自托管 runner
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Deploy
        run: |
          cd /home/github-deploy/_work/goose
          git pull origin main
          bun install
          bun run build
          pm2 start dist/app.js --name goose