name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted    #使用自托管 runner
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Deploy
        run: |
          # 2. 必须显式加载环境变量（关键：Self-hosted Runner 默认不带这些路径）
          export PATH="$HOME/.bun/bin:$PATH"
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          # 3. 使用环境变量 $GITHUB_WORKSPACE 自动定位目录
          cd $GITHUB_WORKSPACE
          pwd
          # 4. 执行安装
          bun install
          
          # 5. 优化 PM2 启动命令：
          # - 使用 reload 实现平滑重启
          # - 如果是第一次运行，reload 失败则执行 start
          pm2 reload goose || pm2 start ～/_work/goose/goose/app.ts --interpreter ~/.bun/bin/bun --name "goose"