export const WORKFLOW_TASK_SELECT = [
  "id",
  "tenant_id",
  "instance_id",
  "instance_node_id",
  "definition_id",
  "version_id",
  "node_id",
  "node_key",
  "node_type",
  "title",
  "status",
  "assignee_employee_id",
  "assignee_role_code",
  "assignee_permission_code",
  "assignee_employee:employees!workflow_tasks_assignee_employee_id_fkey(id, name, avatar)",
  "due_at",
  "completed_by",
  "completed_at",
  "created_at",
  "updated_at",
  [
    "instance:workflow_instances!inner(",
    "id, subject_type, subject_id, status, current_node_key, current_node_snapshot",
    ")",
  ].join(""),
].join(", ");
